### ISSUE TITLE
.map(_) implementation

### ISSUE THREAD

**Issue by llogiq** [fizyk20/generic-array#11]
I have a `.map(_)` implementation that can map a function over a slice or `GenericArray<_, _>` producing another `GenericArray`. It uses leak amplification to be (hopefully) panic-safe. We should also be able to use it to clone `GenericArray`s (both from slice or otherwise).

Will try to set up a PR shortly.

**Comment by fizyk20** [comment]
PR is merged, so I'm closing the issue.
