### ISSUE TITLE
support try_form? 

### ISSUE THREAD

**Issue by bigdogs** [fizyk20/generic-array#119]
GenericArray::from_slice(&[u8) will panic if slice length is not match. It would be great to provide a Result version, e.g. (GenericArray::try_from_slice(&[u8) -> Result<Self, LengthNotMatch>)

**Comment by bigdogs** [comment]
and is there a method to get the array length from GenericArray?  If `try_from` is not possible to support, I can check slice size before 'GenericArray::from_slice', But I didn't find any method for this.

**Comment by orthecreedence** [comment]
I do this outside the crate:

```
let arr: [u8; 32] = some_vec.try_from()?;
let genarr = GenericArray::from(arr);
```

**Comment by agostbiro** [comment]
There is also [from_exact_iter](https://fizyk20.github.io/generic-array/generic_array/struct.GenericArray.html#method.from_exact_iter) that will return `None` if the sizes don't match.
