### ISSUE TITLE
Do not use typenum since seems no more maintained

### ISSUE THREAD

**Issue by dibericky** [fizyk20/generic-array#128]
This crate uses typenum as dependency but that one seems no more maintained (last commit on December 2021) and has issues with Mac OS Apple Silicon: https://github.com/paholg/typenum/issues/182

I'd suggest to not use it in order to make generic-array usable on Apple Silicon

**Comment by novacrazy** [comment]
`typenum` is a fundamental component of `generic-array`. Literally not possible without it.

What you linked to is actually an internal compiler error, which should be reported to the Rust compiler project instead.

**Comment by paholg** [comment]
FYI: typenum is not unmaintained, it's just very stable. And folks still contribute new features from time to time.
