### ISSUE TITLE
Is the reason for this crate still valid with const generics? If so, maybe update docs.

### ISSUE THREAD

**Issue by deepink-mas** [fizyk20/generic-array#135]
This is the motivating example for this crate (slight difference between README and docs):
```
struct Foo<T, N> {
    data: [T; N]
}
```

Could this not be written (in recent Rust versions) as:
```
struct Foo<T, const N: usize> {
    data: [T; N]
}
```

If not, maybe update the motivating example?

**Comment by nathan-at-least** [comment]
I had the same question and just reviewed [the 1.0.0-alpha.1 docs](https://docs.rs/generic-array/1.0.0-alpha.1/generic_array/) and it does indeed clarify the rationale for this crate  (as claimed in #138). This includes an example of limitations of const generics which this crate addresses.

Thanks!
