### ISSUE TITLE
Question: Getting generaic array size as constant

### ISSUE THREAD

**Issue by HaronK** [fizyk20/generic-array#136]
Hi!

Is there a way to get generic array size as constant value?
I have Nonce type from Aes crate declared as GenericArray<u8, U12>.
So can I do something like Nonce::SIZE to get an array size?

I was looking in the documentation but could not find anything.

Thanks!

**Comment by novacrazy** [comment]
Yes, you can use `typenum::Unsigned` to get the const value of a valid `ArrayLength<T>` associated type.

```rust
use aes_gcm_siv::{Aes256GcmSiv, AeadCore};
use generic_array::typenum::Unsigned;

fn main() {
    let length = <<Aes256GcmSiv as AeadCore>::NonceSize as Unsigned>::USIZE;
}
```

which for that crate equals the size in the `Nonce` type.

**Comment by HaronK** [comment]
Yeah, that helped. Would be nice to have it as a separate const function in the future.
In any case, thank you @novacrazy!
