### ISSUE TITLE
How about the speed?

### ISSUE THREAD

**Issue by oilel** [fizyk20/generic-array#141]
How fast is GenericArray::from()?

**Comment by novacrazy** [comment]
It's a no-op with any opt-level > 0. It's just a transmute.

**Comment by oilel** [comment]
> It's a no-op with any opt-level > 0

So why aren't arrays or vectors generic?

**Comment by novacrazy** [comment]
I don't fully understand your question. Currently, in pre-1.0 versions of `generic-array`, it was designed to be used in versions of Rust without const-generics, so for what size of arrays are supported with `From` is limited.
