### ISSUE TITLE
Add constructor to create a `&GenericArray<T, N>` from `&[T, N]`

### ISSUE THREAD

**Issue by keks** [fizyk20/generic-array#150]
Currently the only way to do this is using `from_slice`, however this doesn't provide type safety w.r.t the length of the array. Having something like `from_array_ref` would be neat.

**Comment by novacrazy** [comment]
`generic-array` 1.0 already has:
```rust
impl<'a, T, const N: usize> From<&'a [T; N]> for &'a GenericArray<T, ConstArrayLength<N>>
where
    Const<N>: IntoArrayLength,
```
and an `&mut` version.

**Comment by keks** [comment]
Huh, I missed that! Nevermind then :)
