### ISSUE TITLE
flatten/unflatten functionality

### ISSUE THREAD

**Issue by Dzuchun** [fizyk20/generic-array#151]
I wonder if there's a way to flatten/unflatten a two-dimensional array. I think that as long as dimensions are properly enforced with the bounds, it should be safe to simply cast between them, since `GenericArray` has the same layout as core array.

It is [trivial to implement anywhere](https://gist.github.com/Dzuchun/ddbe7cee94e602a95fc0aa6ffc96db53), but I feel like it should be a part of this crate.

**Comment by Dzuchun** [comment]
Looks good to me!
(should we close the issue, then?)

**Comment by novacrazy** [comment]
I haven't published it yet, was attempting some other things while I was at it. The lack of const given it's implemented via a trait is a non-issue, then?

**Comment by Dzuchun** [comment]
Yeah, I used const in the gist just because I could.

These methods not being const is consistent with rest of the crate, so that's ok.

**Comment by novacrazy** [comment]
Published in v1.1.1
