### ISSUE TITLE
Is it possible to extract the length from a GenericArray?

### ISSUE THREAD

**Issue by MaikKlein** [fizyk20/generic-array#16]
I want to implement a Matrix type

```
struct Matrix<T, N, M>
    where N: ArrayLength<T>,
          M: ArrayLength<GenericArray<T, N>>{
    data: GenericArray<GenericArray<T, N>, M>
}

type Mat3x2f = Matrix<f32, U3, U2>;
```

I would want to implement a `transpose` function that would transform a `Mat3x2f ` to a `Mat2x3f `.

```
impl<T, N, M> Matrix<T, N, M>
    where N: ArrayLength<T>,
          M: ArrayLength<GenericArray<T, N>>{
    fn tranpose(&self) -> ???
}
```

The problem that I have is that `ArrayLength` depends on the type for a `GenericArray`, which means I can't just write

```
impl<T, N, M> Matrix<T, N, M>
    where N: ArrayLength<T>,
          M: ArrayLength<GenericArray<T, N>>{
    fn tranpose(&self) -> Matrix<T, M, N>{..}
}
```

Any idea if that could be achieved with `GenericArray`?

**Comment by fizyk20** [comment]
This might work, although it isn't very pretty:

```rust
impl<T, N, M> Matrix<T, N, M>
    where N: ArrayLength<T> + ArrayLength<GenericArray<T, M>>,
          M: ArrayLength<T> + ArrayLength<GenericArray<T, N>>{
    fn tranpose(&self) -> Matrix<T, M, N> {
    //...
    }
}
```

Also, you could use just one `GenericArray` with length `N*M` (`<N as Mul<M>>::Output`) - that's basically what I'm doing in `differential-geometry`.

**Comment by MaikKlein** [comment]
Thanks that works, I didn't know you could implement the same trait twice with different arguments.
