### ISSUE TITLE
Remove no_std feature

### ISSUE THREAD

**Issue by newpavlov** [fizyk20/generic-array#19]
`no_std` feature got [deprecated](https://github.com/paholg/typenum/blob/98339f0ea3d4b7f1476f9e2f77be2bf5cbfcbfaa/build.rs#L66) in `typenum` and this crate does not use it at all, so there is no reason to keep it.

P.S.: Also this issue will be a good reason to bump a minor version. ;)

**Comment by fizyk20** [comment]
Makes sense, thanks :) Won't it conflict with crates using `std`, though? From what I could gather, it looks like it won't, but I need to make sure ;)

**Comment by newpavlov** [comment]
>Won't it conflict with crates using `std`, though?
I've used `no_std` crates from `std` ones, no problems so far. I will be very surprised if such problem arise and I think we should qualify it as a bug.
>Oh, and by the way - why 0.5.1 and not 0.5.0 in the PR?
My mistake, will fix it.

**Comment by fizyk20** [comment]
Awesome, thanks :)

**Comment by bluss** [comment]
Nodrop links to std by default as well (you can opt out).

It's hard to get rid of std.. :wink:

**Comment by bluss** [comment]
Since the previous `no_std` feature in your crate was subtractive, I'll put in a reminder that crate features need to be additive due to how they work in cargo. Nodrop has an example of this, `std` is an additive (but default) feature.
