### ISSUE TITLE
Building with serde feature does not work with Serde versions >= 8.0

### ISSUE THREAD

**Issue by ashleysommer** [fizyk20/generic-array#21]
See this commit to the `serde` project on 11 July:
https://github.com/serde-rs/serde/commit/99038b044ea512af7bac24f42ee54a6b0bf48214
This removed `SeqVisitor` and replaced it with `SeqSerializer`. The `impl_serde.rs` code in `generic-array` still uses the `SeqVisitor`, thus does not compile with newer versions of `serde`.
The commit status show that is has been in effect for all of these versions of `serde`:
`v0.8.8 v0.8.7 v0.8.6 v0.8.5 v0.8.4 v0.8.3 v0.8.2 v0.8.1 v0.8.0 v0.8.0-rc3 v0.8.0-rc2 v0.8.0-rc1`,
however in the `Cargo.toml` file `generic-array` indicates preference for `serde = "~0.8"`

**Comment by fizyk20** [comment]
Heh, I guess that's what you get for not testing if all features work after merging a pull request ;) Unfortunately I have no time to fix it at the moment, but I should be able to get to it tomorrow.

**Comment by fizyk20** [comment]
Ok, should be fixed in 0.5.1 :)
