### ISSUE TITLE
Can GenericArray be Copy?

### ISSUE THREAD

**Issue by bluss** [fizyk20/generic-array#23]
Can GenericArray be Copy? It would be useful if it was, when the element type is.

**Comment by fizyk20** [comment]
It should be already:

https://github.com/fizyk20/generic-array/blob/285f045c5d7bce3fcd086687a1d53dc81b03659a/src/lib.rs#L205
https://github.com/fizyk20/generic-array/blob/285f045c5d7bce3fcd086687a1d53dc81b03659a/src/lib.rs#L86
https://github.com/fizyk20/generic-array/blob/285f045c5d7bce3fcd086687a1d53dc81b03659a/src/lib.rs#L107

If this doesn't work, then we have a problem ;)

**Comment by fizyk20** [comment]
I added a test that checks whether the Copy implementation works and it indeed does, so I'm closing the issue :)

**Comment by bluss** [comment]
Great, thanks for the answer. I just didn't see it in the docs.

**Comment by fizyk20** [comment]
Yeah, the docs could use some updatng ;)
