### ISSUE TITLE
impl Default

### ISSUE THREAD

**Issue by millardjn** [fizyk20/generic-array#25]
Hi, are you ok with adding a impl Default for GenericArray<T:Default, U> ?
This is essentially the same as the current new() method, but would allow initialising nested generic arrays.

**Comment by fizyk20** [comment]
Sure, makes sense :) If you make a PR, I'll gladly accept it :)

**Comment by fizyk20** [comment]
Resolved in #26.

**Comment by adeschamps** [comment]
Just in time for me to use this feature! 

Could we get a new release so I can have my Cargo.toml depend on crates instead of the git repo?
