### ISSUE TITLE
GenericArray lacks a clean, obvious way to convert to &[u8]

### ISSUE THREAD

**Issue by tomjakubowski** [fizyk20/generic-array#28]
I realize that this is somewhat redundant with the Deref impl, but using a GenericArray in a function call that takes a `&[u8]` is a bit awkward at the moment. You have to choose between:

```
foo(&*myarr);
```

or:

```
foo(&myarr[..])
```

or:

```
use std::deref::Deref;
foo(myarr.deref());
```

which are all somewhat ugly or unclear (especially to Rust newbies). How about aping Vec and providing a method `GenericArray::as_slice()`, used like:

```
foo(myarr.as_slice());
```

**Comment by fizyk20** [comment]
Resolved in commit 2156193
