### ISSUE TITLE
Add compatibility to work with serde 0.9

### ISSUE THREAD

**Issue by Pratyush** [fizyk20/generic-array#33]
Hi,

Would it be possible to make the crate compatible with serde 0.9? 0.9 makes life much easier for `no_std` users by introducing `derive` for `Serialize` and `Deserialize` in `no_std`. Thanks!

**Comment by fizyk20** [comment]
Version 0.7.0 is now compatible with serde 0.9 :)

**Comment by Pratyush** [comment]
Thanks for the prompt response =)
