### ISSUE TITLE
Issues with Eq

### ISSUE THREAD

**Issue by Pratyush** [fizyk20/generic-array#34]
Hi,

I'm trying to use a `GenericArray` inside a struct wrapping a BtreeSet, but when I instantiate the Array with a numtype (say `U1`), I get compile-time errors saying that

the trait `core::cmp::Eq` is not implemented for `generic_array::GenericArrayImplOdd<u8, ()>`

For reference, here's a simplified version of my code:

```
struct Block<N> 
      where N: ArrayLength<u8>,
            N::ArrayType: Copy + Eq
{
    content: GenericArray<u8, N>
}

struct Container<N>
      where N: ArrayLength<u8>,
            N::ArrayType: Copy + Eq
{
    set: BTreeSet<Block<N>>
}
```
Trying to instantiate Container results in the above error. Any tips on how to fix this? Using just a BTreeSet (not wrapped in another struct) doesn't result in these problems (I think).

**Comment by Pratyush** [comment]
Hmm I fixed by removing the `Eq` constraints on `N::ArrayType`. I'm having similar issues with respect to Serialize and Deserialize, but maybe that's for another issue.

**Comment by fizyk20** [comment]
Hm, but why would you need constraints on `N::ArrayType`? It is an implementation detail, you shouldn't have to bother with it.

**Comment by Pratyush** [comment]
I thought I needed the constraints because I'm deriving `Eq` and `PartialEq` on the `Block` struct, and deriving `Copy` required adding a `Copy` constraint on `N::ArrayType`.

This turned out to be unnecessary.

**Comment by fizyk20** [comment]
`GenericArray<T,N>` should be `Copy` when `T` is `Copy`, so that should indeed be unnecessary. It could be more problematic with `Eq`, as I haven't implemented it for `GenericArray`.

But I take it this problem is solved and I can close the issue?

**Comment by Pratyush** [comment]
Just to clarify, I did have to specify that `N::ArrayType: Copy` when deriving `Copy` on `Block`, even though `T = u8` should take care of this(?). I followed #24. Having the `Eq` constraint was unnecessary.

And yup, the issue is now solved; thanks for the help =).
