### ISSUE TITLE
Deriving Serialize & Deserialize

### ISSUE THREAD

**Issue by Pratyush** [fizyk20/generic-array#35]
I'm having issues with deriving (and then using) `Serialize` and `Deserialize` on structs that contain a `GenericArray`. For example, the code below doesn't compile:

```
extern crate serde;
#[macro_use]
extern crate serde_derive;
#[macro_use]
extern crate generic_array;
extern crate bincode;

use generic_array::{GenericArray, ArrayLength};
use generic_array::typenum;

#[derive(Serialize, Deserialize)]
struct Block<N>
    where N: ArrayLength<u8>
{
    content: GenericArray<u8, N>,
}

fn main() {
    let block: Block<typenum::U1> = Block { content: arr![u8; 1] };
    bincode::serialize(&block, bincode::SizeLimit::Infinite);
}
```

I get the following error:

```
error[E0277]: the trait bound `generic_array::<unnamed>::UInt<generic_array::<unnamed>::UTerm, generic_array::<unnamed>::B1>: serde::Serialize` is not satisfied
```

**Comment by fizyk20** [comment]
I wonder whether you should run this error by the authors of Serde - it looks like an issue with the code generated by `#[derive]` - or maybe there are some requirements I don't know of. The weird part is that the error suggests that `U1` should be serializable for this to work - I have no idea why.

I take it the array itself is serializable without problems?

**Comment by Pratyush** [comment]
Oops, I forgot I'd opened this issue. I asked this question on [/r/rust](www.reddit.com/r/rust), and got a very helpful [answer](https://www.reddit.com/r/rust/comments/5z3t5j/hey_rustaceans_got_an_easy_question_ask_here/dewmhjl/?context=3).

**Comment by fizyk20** [comment]
So it is solved, then? :) Nice one about this `#[serde]`, I had no idea such a thing exists!

**Comment by Pratyush** [comment]
Yup, it's solved =). I'll close this issue.

**Comment by maisiliym** [comment]
Should there be a note in readme saying 'search reddit for more documentation' ?
