### ISSUE TITLE
Default doesn't work

### ISSUE THREAD

**Issue by WaDelma** [fizyk20/generic-array#37]
If I try to build:
````
GenericArray::<u8, U1>::default();
````
with `rustc 1.17.0-nightly (3da40237e 2017-03-24)` I get error:
````
error: no associated item named `default` found for type `generic_array::GenericArray<u8, typenum::UInt<typenum::UTerm, typenum::B1>>` in the current scope
````

**Comment by fizyk20** [comment]
I can't reproduce this - I even added a test and it seems to work. Does it still happen for you?

**Comment by WaDelma** [comment]
Hmmm.. What is going on then? I tried with latest nightly and stable and they both give that error for me.

**Comment by fizyk20** [comment]
Could you give some more context, then? Maybe it's something caused by some other part of the code.

**Comment by WaDelma** [comment]
Extremely weird. I just cloned the project and ran tests and they succeeded well.

**Comment by WaDelma** [comment]
[Here](https://github.com/WaDelma/galgebra/blob/master/src/generic.rs#L105) is the code.
I don't see anything causing it...

**Comment by fizyk20** [comment]
```generic-array = "0.2"```
I think I've found the problem ;)

**Comment by WaDelma** [comment]
Ah.... Whoops.

**Comment by WaDelma** [comment]
Well that error went a way. Thanks for helping me to debug my stupid mistakes :D

**Comment by fizyk20** [comment]
Glad it worked and you're welcome :)
