### ISSUE TITLE
GenericArray doesn't implement Ord

### ISSUE THREAD

**Issue by ababo** [fizyk20/generic-array#38]

**Comment by ababo** [comment]
Also it doesn't implement implement FromIterator. I suggest to look into std to figure out what traits are implemented by slice/vector.

**Comment by fizyk20** [comment]
FromIterator doesn't really make sense for an array with size defined at compile time, I think.

**Comment by ababo** [comment]
Not sure. Just now wrote an implementation of merkle-tree and this tree returns a vector of node hashes (generic vectors). It would be nice to build such a vector by mapping in that case.

**Comment by fizyk20** [comment]
But how would it work? An iterator can iterate over data of arbitrary length, known only at runtime. The type you are collecting into must be known at compile time - and in the case of arrays and GenericArrays the size is a part of the type. Let's say I'll be collecting into `GenericArray<_, U32>` - what should the code do if the length of the data isn't 32? Panic, collect as much as it can (but what if the type in the array doesn't implement `Default` and we have too few elements)? I don't think there is a reasonable choice and arrays indeed don't implement `FromIterator`, either.

A vector of course makes sense - but this use case is already covered by `Vec`.

**Comment by ababo** [comment]
I'm talking about Vec<GenericArray<...>>. Since hash (e.g. SHA-2, 256bit) is a fixed size block of data we can represent it by GenericArray. When I collect such hashes from my storage into Vec<GenericArray<u8, U32>> it's nice to use the map(...).collect(...) sequence.

**Comment by fizyk20** [comment]
Oh, I see. But isn't that covered by the fact that `FromIterator` is implemented for `Vec<T>`?

**Comment by ababo** [comment]
AFAIK, this trait should be implemented by a type which is collected into container, not by the container itself.

**Comment by fizyk20** [comment]
https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect

This indicates that the return type of `collect` has to implement `FromIterator` - in this case it's the `Vec`. This makes sense, as it is the container that is being constructed from the iterator, not the elements.
