### ISSUE TITLE
Having different versions of generic-array breaks the build

### ISSUE THREAD

**Issue by golddranks** [fizyk20/generic-array#49]
Lately, there has been some breakages when crates that depend on different versions (0.7 and 0.8) of generic-array are being used in the same build. The breakage is due to `cargo update` not finding compatible crates. See https://github.com/rust-lang/cargo/issues/4474 It's unclear to me whether the build would actually break, because it fails already when `cargo update` is being performed.

See also https://github.com/durch/rust-s3/issues/18 and https://github.com/sfackler/rust-postgres/issues/290

An example of the breaking which I'm familiar with is `rust-s3` and `postgres`. However, these crates are fully independent and don't interact. They don't even expose any `generic-array` types in their API, as far as I know.

Do you know as the author of this crate any reason why different versions of this crate would break the build?

**Comment by sfackler** [comment]
This is due to this dependency constraint in 0.7: https://github.com/fizyk20/generic-array/blob/0.7.2/Cargo.toml#L15, which isn't compatible with other semver compatible versions of typenum. Cargo will refuse to have copies of both typenum 1.5 and 1.7 in the crate graph at the same time.

**Comment by fizyk20** [comment]
Oh right, that was silly. Do you have any idea if it's possible to publish 0.7.3 even after 0.8 has been published? If yes, then I could fix that constraint and crates depending on 0.7 would probably be fixed.

**Comment by sfackler** [comment]
Yep it should work fine - there aren't any restrictions on publishing things "out of order".

**Comment by fizyk20** [comment]
Awesome - I just published 0.7.3 which should fix this problem. I'll close this issue after you confirm that it is indeed fixed :)

**Comment by fizyk20** [comment]
Looks like it's fixed, so I'm closing this.
