### ISSUE TITLE
Genric array is not copy generically

### ISSUE THREAD

**Issue by matklad** [fizyk20/generic-array#53]
Hi!

While `GenericArray<u8, L>` is `Copy` for each length, it's not `Copy` for all lengths:

```Rust
fn assert_is_copy<T: Copy>() {}

fn test_concrete_array_is_copy() { // this works
    assert_is_copy::<GenericArray<u8, U32>>()
}

fn test_abstract_array_is_copy<L: ArrayLength<u8>>() { // this fails to compiler
    assert_is_copy::<GenericArray<u8, L>>()
}
```

I am not sure if it's possible to fix this in a good way though :( What we want is a bound `where T: Copy => Self::ArrayType: Copy` for `ArrayLength`, but I think it's not possible to express this in Rust? What we might do is to introduce a second, `CopyGenericArray` struct with explicit `T: Copy` bound, but this feels pretty ugly.

**Comment by fizyk20** [comment]
Yeah, I think this might be a shortcoming in Rust's "reasoning" about traits. `Copy` is implemented for `GenericArray<T, N>` where `T: Copy`, so this should work.

Adding a `GenericArray<u8, L>: Copy` constraint to the last function should work. It's ugly, but it's the only way I know of to satisfy the compiler in this case.

**Comment by fizyk20** [comment]
Since there are no further comments, I'll close this issue.

**Comment by gnzlbg** [comment]
> What we might do is to introduce a second, CopyGenericArray struct with explicit T: Copy bound, but this feels pretty ugly.

@matklad that is less ugly than what @fizyk20 suggests: 

> Adding a GenericArray<u8, L>: Copy constraint

which means adding that constraint everywhere instead of just using a different type.
