### ISSUE TITLE
Use associated constants for ArrayLength?

### ISSUE THREAD

**Issue by matklad** [fizyk20/generic-array#54]
Hi!

Rust recently gained an ability to specify associated constants in traits, and I wonder if we can use it to simplify GeneritArray. My current experiments are here: https://github.com/matklad/generic-array/commit/20be18b7e941f8f0da739134e465773f8bafc632

Looks like it's not working at this time though :(

**Comment by burdges** [comment]
Associated constants do not work in array lengths yet https://github.com/rust-lang/rust/issues/44168 not even on nightly.

I'd think folks should remove the dependency on generic-array entirely once that bug gets fixed and all the bits eventually get stabilized.  I donno if there is any need to change this crate, merely phase it out.

**Comment by matklad** [comment]
Yeah, I've played a bit more with it and I see now the limitations of associated constants, and it's reasonable to asume that, once they are fixed, we'll have proper const type parameters!
