### ISSUE TITLE
Possible safety issue in the future

### ISSUE THREAD

**Issue by sellibitze** [fizyk20/generic-array#6]
I noticed code like this

```rust
	let mut res: GenericArray<T, N> = unsafe { mem::zeroed() };
	for i in 0..N::reify() as usize {
		res[i] = T::default();
	}
	res
```

To the best of my knowledge, this is problematic. You are relying on an "undocumented" implementation detail that might change in the future. The drop flags might be stored out-of-band in the future in which case you can't set a non-trival `T` to be in a "dropped state" by zeroing its memory location.

A slightly more correct (as in relying less on undocumented implementation details) would be to use `std::ptr::write` instead of the assignments:

```Rust
		ptr::write(&mut res[i], T::default());
```

But if you don't want to rely on in-band drop flags (being zeroed) you might also have to rethink panic-safety. Perhaps bluss' `nodrop` create could help.

**Comment by fizyk20** [comment]
Thanks for the heads up. I wasn't aware of how drop flags work, actually. This could indeed be problematic.

I will check `nodrop`. Meanwhile, do you think restricting `T` to be `Copy` would solve the safety problem and be an acceptable temporary workaround?
