### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by fizyk20** [fizyk20/generic-array#60]
Title says all. Intended as a reminder to myself - unless anyone else wants to go through the project history and detail the changes over time?

**Comment by novacrazy** [comment]
How is this?

* **`< 0.3.0`**
    * Initial implementation in late 2015
* **`0.3.0`**
    * Implement `IntoIter` for `GenericArray`
    * Add `map` method
    * Add optional `serde` (de)serialization support feature.
* **`0.4.0`**
    * Re-export `typenum`
* **`0.5.0`**
    * Update `serde`
    * remove `no_std` feature, fixed #19 
* **`0.6.0`**
    * Fixed #30 
    * Implement `Default` for `GenericArray`
    * Implement `LowerHex` and `UpperHex` for `GenericArray<u8, N>`
    * Use `precision` formatting field in hex representation
    * Add `as_slice`, `as_mut_slice`
    * Remove `GenericArray::new` in favor of `Default` trait
    * Add `from_slice` and `from_mut_slice`
    * `no_std` and `core` for crate.
* **`0.7.0`**
    * Upgrade `serde` to `0.9`
    * Make `serde` with `no_std`
    * Implement `PartialOrd`/`Ord` for `GenericArray`
* **`0.8.0`**
    * Implement `AsRef`, `AsMut`, `Borrow`, `BorrowMut`, `Hash` for `GenericArray`
    * Update `serde` to `1.0`
    * Update `typenum`
    * Make macro `arr!` non-cloning
    * Implement `From<[T; N]>` up to `N=32`
    * Fix #45 
* **`0.9.0`**
    * Rewrite construction methods to be well-defined in panic situations, correctly dropping elements.
    * `NoDrop` crate replaced by `ManuallyDrop` as it became stable in Rust core.
    * Add optimized `map`/`map_ref` and `zip`/`zip_ref` methods to `GenericArray`
* **`0.10.0`**
    * Add `GenericSequence`, `Lengthen`, `Shorten`, `Split` and `Concat` traits.
    * Redefine `transmute` to avert errors.
* **Unreleased**
    * Redesign `GenericSequence` with an emphasis on use in generic type parameters.
    * Add `MappedGenericSequence` and `FunctionalSequence`
        * Implements optimized `map`, `zip` and `fold` for `GenericArray`, `&GenericArray` and `&mut GenericArray`
    * Remove `map_ref`, `zip_ref` and `map_slice`
        * `map_slice` is now equivalent to `GenericArray::from_iter(slice.iter().map(...))`

Markdown source in gist: https://gist.github.com/novacrazy/c9ec554656055e050cc0a4029b5041af

**Comment by novacrazy** [comment]
Do you think we could get a new release out this week? If there is anything else I can help with I'd be happy to.

**Comment by fizyk20** [comment]
That's awesome! I'll probably use it as is, thanks! :) Regarding the release, yeah, I think so - I think the latest changes deserve that. I just need a few free moments to go through everything, which I recently didn't have, but hopefully will tomorrow or the day after :)

**Comment by fizyk20** [comment]
I finally got to adding this changelog - I just reversed the sequence of versions, so that the latest one is on top, but other than that I didn't change it. Thanks again! :)

**Comment by novacrazy** [comment]
Cool, and thanks for publishing a new version!
