### ISSUE TITLE
Add 0.12.0 release tag

### ISSUE THREAD

**Issue by garious** [fizyk20/generic-array#67]
Can you add a release tag to github? If I spot a bug and am unable to upgrade, I'd like the option to fork locally from that release tag. Thanks!

**Comment by garious** [comment]
By the way, thanks for that bincode serialization fix. I'll upgrade to 0.12 for just that!

**Comment by novacrazy** [comment]
Alright, added two releases, one for current master and one for before the serialization fix was applied.

Hope that helps!
