### ISSUE TITLE
Implement `FusedIterator` for `GenericArrayIter`

### ISSUE THREAD

**Issue by novacrazy** [fizyk20/generic-array#72]
@fizyk20 Do we have a policy on minimum Rust version required?

[`Fusediterator`](https://doc.rust-lang.org/std/iter/trait.FusedIterator.html) was stabilized in Rust 1.26.0 almost a year ago, and the standard library methods use specialization internally to improve performance for fused iterators, so it would be nice to use it.

[`ptr::add`](https://doc.rust-lang.org/std/primitive.pointer.html#method.add) was stabilized in 1.26 as well, which would be nice to use.

**Comment by fizyk20** [comment]
Well, I don't have one ;)

What are the possible reasons for sticking with an older version of Rust, anyway? I'm wondering who would be affected by an incompatibility with older versions.

There is also #70 which would require Rust 1.30, and which would also be nice to have (I just stumbled upon the issue it fixes in my own code today).

**Comment by novacrazy** [comment]
I'm facepalming right now. I tried testing features on 1.26, only to find out the stuff I literally just published requires 1.27. (`rfold`)

Well, then, I guess it's safe to use 1.26 features. 

Might as well bump to 1.30/Rust 2018 and merge #70 while we're at it.

**Comment by novacrazy** [comment]
Alright, I published two new releases.

* 0.12.2 - Added `FusedIterator` only.
* 0.13.0 - Added #70 and bumped minimum required version to 1.30.1

1.30.1 felt a bit too recent to be a minor release. Considering how fundamental this crate is to the ecosystem, I don't want to break too much.

Probably in six months or so we can switch over to Rust 2018 entirely.

**Comment by fizyk20** [comment]
That makes sense. Thank you!
