### ISSUE TITLE
generic-array v0.12.1 broke builds on pre 1.27 Rust

### ISSUE THREAD

**Issue by newpavlov** [fizyk20/generic-array#73]
In RustCrypto we test MSRV and recent `generic-array` broke our promise to support Rust 1.21 and later dues to the usage of `rfold`. Since you've already published v0.13.0, maybe it's worth to yank v0.12.1 and v0.12.2?

**Comment by novacrazy** [comment]
I was hoping updating to a nearly year-old version of Rust wouldn't break too much, but yes I'll go ahead and yank those right now.

Done.

**Comment by newpavlov** [comment]
Thank you!

Well, it's not like it broke someone's build (yet), but it was caught with our CI setup. To be honest I don't think that such conservative MSRV guarantees are too important (e.g. we had `block-buffer` version which broke it published for a week and no one complained), but in my opinion it's still better to upheld to given promises.
