### ISSUE TITLE
Borrowing .map()

### ISSUE THREAD

**Issue by Reconcyl** [fizyk20/generic-array#76]
I have `array: GenericArray<T, N>` and a function `f: fn(&T) -> U`. I want to be able to obtain a `GenericArray<U, N>`.

Right now I can't see any way to do this other than `array.clone().map(|x| f(&x))`. It would be useful for there to be a way to do this without cloning the array. This could be added either in the form of a `FunctionalSequence::map_ref` method that directly implemented this functionality or through another method to convert a `&GenericArray<T, N>` to a `GenericArray<&T, N>`.

If I'm not just missing something and this functionality is judged worthwhile to add, I can give implementing it a shot.

**Comment by novacrazy** [comment]
You should just be able to do `(&array).map(...)`, as `&GenericArray` also implements `FunctionalSequence`

**Comment by Reconcyl** [comment]
Ah, I didn't see that. Thanks!

**Comment by novacrazy** [comment]
No problem at all. Feel free to close this issue if you have no further questions.
