### ISSUE TITLE
Implement Into trait 

### ISSUE THREAD

**Issue by newpavlov** [fizyk20/generic-array#78]
It would be nice to have the following traits:
```rust
impl<T> Into<[T; 1]> for GenericArray<T, U1> { .. }
impl<T> Into<[T; 2]> for GenericArray<T, U2> { .. }
// up to 32, for 48 and 64
```
One use-case is to easily convert hashes in RustCrypto crates from `GenericArray` to arrays. And it would be great if you'll publish a backport for v0.12, which is currently used by RustCrypto crates.

**Comment by burdges** [comment]
Just fyi, those collide with the generic impl, so you should do this using From instead.

**Comment by newpavlov** [comment]
Right now we have only `impl<T> From<[T; 1]> for GenericArray<T, U1>`, which imply `impl<T> Into<GenericArray<T, U1>> for [T; 1]`, so those impls should not conflict with the proposed ones.

**Comment by novacrazy** [comment]
It doesn't conflict. Just tested it. Will update the crate soon.

**Comment by novacrazy** [comment]
Added in version `0.13.1`

**Comment by newpavlov** [comment]
Can you also please publish a backport for v0.12?

**Comment by novacrazy** [comment]
Backported to 0.12.3

**Comment by newpavlov** [comment]
Thank you!

**Comment by burdges** [comment]
Ahh, I expected you'd want `impl<T> From<GenericArray<T, U1>> for [T; 1] { .. }` to avoid conflicting with the generic `From` to `Into`, but maybe this falls under the orphan rules being too strict, as both `From` and `[T; 1]` come from elsewhere.  I see..
