### ISSUE TITLE
Panic safety issues

### ISSUE THREAD

**Issue by bluss** [fizyk20/generic-array#8]
I haven't reviewed the whole library, but I noticed a bug and I wanted to mention it.

Using `mem::uninitialized` is tricky for general values. Is generic-array restricted to only `Copy` types?

The `new` and `from_slice` methods are good examples. An unintialized array is created on [line 136](https://github.com/fizyk20/generic-array/blob/master/src/lib.rs#L136), on the next line, ***user supplied function*** `T::default()` is called. The problem is that the array will run its destructor if there is a panic, and we can't rule out panic since the default function is arbitrary user code.

The `from_slice` method has the same problem (the arbitrary user code is `.clone()`).

Feel free to ask any questions you may have.

**Comment by fizyk20** [comment]
Thanks for the heads up!

GenericArray isn't restricted to only `Copy` types. I've thought about it, but I had some use cases where that was too limiting. Looks like you're right though, unfortunately, but I have currently no idea how to fix it. Do you have any hints?

**Comment by bluss** [comment]
I wrote arrayvec so I only know how to solve the soundness issues I found while implemented it (and one reported after).

Arrayvec has worse problems because it models an array that can be partially filled (just like a vector). Unfortunately, any time we use `uninitialized`, the time between that call and the moment the array is fully initialized, we're in the same situation — the array is partially filled. With risk of `panic`, this becomes important.

You can use the `NoDrop` approach arrayvec uses, to make sure array elements are only dropped explicitly, and never automatically.

Alternatively, you can use `std::panic::recover` to in some other way resolve the panic safety issues.

**Comment by fizyk20** [comment]
Should be fixed in 0.3.0.
