### ISSUE TITLE
Concatenating two arrays

### ISSUE THREAD

**Issue by cbeck88** [fizyk20/generic-array#84]
It would be really nice if there was a syntax like

```
join(arr1, arr2)
```

that produced a new array of the correct length, if both input arrays have the same type.

Doing it manually with `copy_from_slice` is less readable, and `copy_from_slice` can panic if you do it wrong, so it would be nice if there is a simpler API that doesn't panic in any scenario.

**Comment by novacrazy** [comment]
Check out the [`Concat`](https://fizyk20.github.io/generic-array/generic_array/sequence/trait.Concat.html) trait.

**Comment by cbeck88** [comment]
thank you!
