### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by nickray** [fizyk20/generic-array#86]
Is there a way to specify that the underlying data should be, e.g., 4-byte aligned?
I am thinking of a syntax similar to https://docs.rs/aligned/0.3.2/aligned/

**Comment by novacrazy** [comment]
You should just be able to specify the alignment on the element type directly. i.e. `GenericArray<Aligned<A4, T>, N>`

**Comment by garbageslam** [comment]
sometimes I found it's important to have over-aligned array types, for example `Aligned<A16, GenericArray<u8, N>>`

I have developed this crate which extends the `aligned` crate to integrate with `generic-array` and extend its traits, to better support aligned array types like that: https://docs.rs/aligned-array/1.0.1/aligned_array/

**Comment by novacrazy** [comment]
There is nothing special I can see that needs to be done within `generic-array` itself to align the arrays. This can be done with wrapper types to align elements or the array itself.

Something as simple as:
```rust
#[repr(align(16))]
struct Test {
    x: i32,
}

pub struct Test2 {
    arr: GenericArray<Test, typenum::U7>,
}
```
results in `type: Test2: 112 bytes, alignment: 16 bytes` with no padding when doing `-Z print-type-sizes`

If I specify `#[repr(align(32))]` on `Test2`, it becomes:
```
type: `Test2`: 128 bytes, alignment: 32 bytes
    field `.arr`: 112 bytes
    end padding: 16 bytes
```

I'm going to go ahead and close this unless something more is required.
